import type { Dispatch } from 'react';

import type {
  ArrangementClip,
  AppView,
  InstrumentType,
  MasterSettings,
  NoteEvent,
  SampleSliceMemory,
  SynthParams,
  TrackSource,
  TransportMode,
} from '../../project/schema';
import type { EditorAction } from './editorTypes';

export const createEditorDispatchers = (dispatch: Dispatch<EditorAction>) => ({
  addArrangerClip: (trackId?: string) => dispatch({ type: 'ADD_ARRANGER_CLIP', trackId }),
  applyMasterSnapshot: (snapshotId: string) => dispatch({ type: 'APPLY_MASTER_SNAPSHOT', snapshotId }),
  applyTrackSnapshot: (trackId: string, snapshotId: string) => dispatch({ type: 'APPLY_TRACK_SNAPSHOT', snapshotId, trackId }),
  applyTrackVoicePreset: (trackId: string, presetId: string) => dispatch({ type: 'APPLY_TRACK_VOICE_PRESET', presetId, trackId }),
  clearPatternAt: (trackId: string, patternIndex: number) => dispatch({ type: 'CLEAR_PATTERN_AT', trackId, patternIndex }),
  clearTrack: (trackId: string) => dispatch({ type: 'CLEAR_TRACK', trackId }),
  createSampleSlice: (trackId: string, slice?: Partial<SampleSliceMemory>) => dispatch({ type: 'CREATE_SAMPLE_SLICE', slice, trackId }),
  createSongMarker: (beat: number, name?: string) => dispatch({ type: 'CREATE_SONG_MARKER', beat, name }),
  createTrack: (trackType: InstrumentType) => dispatch({ type: 'CREATE_TRACK', trackType }),
  deleteMasterSnapshot: (snapshotId: string) => dispatch({ type: 'DELETE_MASTER_SNAPSHOT', snapshotId }),
  deleteSampleSlice: (trackId: string, sliceIndex: number) => dispatch({ type: 'DELETE_SAMPLE_SLICE', sliceIndex, trackId }),
  deleteTrackSnapshot: (snapshotId: string) => dispatch({ type: 'DELETE_TRACK_SNAPSHOT', snapshotId }),
  duplicateArrangerClip: (clipId: string) => dispatch({ type: 'DUPLICATE_ARRANGER_CLIP', clipId }),
  duplicateSongRange: (startBeat: number, endBeat: number, label?: string) => dispatch({ type: 'DUPLICATE_SONG_RANGE', endBeat, label, startBeat }),
  duplicateTrack: (trackId: string) => dispatch({ type: 'DUPLICATE_TRACK', trackId }),
  loopArrangerClip: (clipId: string, copies: number) => dispatch({ type: 'LOOP_ARRANGER_CLIP', clipId, copies }),
  makeClipPatternUnique: (clipId: string) => dispatch({ type: 'MAKE_CLIP_PATTERN_UNIQUE', clipId }),
  moveTrack: (trackId: string, direction: 'up' | 'down') => dispatch({ type: 'MOVE_TRACK', direction, trackId }),
  redo: () => dispatch({ type: 'REDO' }),
  removeArrangerClip: (clipId: string) => dispatch({ type: 'REMOVE_ARRANGER_CLIP', clipId }),
  removeSongMarker: (markerId: string) => dispatch({ type: 'REMOVE_SONG_MARKER', markerId }),
  removeTrack: (trackId: string) => dispatch({ type: 'REMOVE_TRACK', trackId }),
  renameProject: (name: string) => dispatch({ type: 'SET_PROJECT_NAME', name }),
  renameTrack: (trackId: string, name: string) => dispatch({ type: 'SET_TRACK_NAME', name, trackId }),
  saveMasterSnapshot: (snapshotId?: string | null) => dispatch({ type: 'SAVE_MASTER_SNAPSHOT', snapshotId }),
  saveTrackSnapshot: (trackId: string, snapshotId?: string | null) => dispatch({ type: 'SAVE_TRACK_SNAPSHOT', snapshotId, trackId }),
  selectSampleSlice: (trackId: string, sliceIndex: number | null) => dispatch({ type: 'SELECT_SAMPLE_SLICE', sliceIndex, trackId }),
  setActiveView: (view: AppView) => dispatch({ type: 'SET_ACTIVE_VIEW', view }),
  setBpm: (bpm: number) => dispatch({ type: 'SET_BPM', bpm }),
  setClipPatternStepSlice: (clipId: string, stepIndex: number, sliceIndex: number | null, note?: string) => dispatch({ type: 'SET_CLIP_PATTERN_STEP_SLICE', clipId, note, sliceIndex, stepIndex }),
  setCountInBars: (bars: number) => dispatch({ type: 'SET_COUNT_IN_BARS', bars }),
  setCurrentPattern: (pattern: number) => dispatch({ type: 'SET_CURRENT_PATTERN', pattern }),
  setLoopRange: (startBeat: number | null, endBeat: number | null) => dispatch({ type: 'SET_LOOP_RANGE', endBeat, startBeat }),
  setMasterSettings: (settings: Partial<MasterSettings>) => dispatch({ type: 'SET_MASTER_SETTINGS', settings }),
  setMetronomeEnabled: (enabled: boolean) => dispatch({ type: 'SET_METRONOME_ENABLED', enabled }),
  setPatternCount: (patternCount: number) => dispatch({ type: 'SET_PATTERN_COUNT', patternCount }),
  setSelectedArrangerClipId: (clipId: string | null) => dispatch({ type: 'SET_SELECTED_ARRANGER_CLIP', clipId }),
  setSettingsOpen: (open: boolean) => dispatch({ type: 'SET_SETTINGS_OPEN', open }),
  setSelectedTrackId: (trackId: string | null) => dispatch({ type: 'SET_SELECTED_TRACK_ID', trackId }),
  setStepsPerPattern: (stepsPerPattern: number) => dispatch({ type: 'SET_STEPS_PER_PATTERN', stepsPerPattern }),
  setTrackParams: (trackId: string, params: Partial<SynthParams>) => dispatch({ type: 'SET_TRACK_PARAMS', params, trackId }),
  setTrackSource: (trackId: string, source: Partial<TrackSource>) => dispatch({ type: 'SET_TRACK_SOURCE', source, trackId }),
  setTransportMode: (mode: TransportMode) => dispatch({ type: 'SET_TRANSPORT_MODE', mode }),
  shiftPattern: (trackId: string, direction: 'left' | 'right') => dispatch({ type: 'SHIFT_PATTERN', direction, trackId }),
  shiftPatternAt: (trackId: string, patternIndex: number, direction: 'left' | 'right') => dispatch({ type: 'SHIFT_PATTERN_AT', direction, trackId, patternIndex }),
  splitArrangerClip: (clipId: string, splitAtBeat?: number) => dispatch({ type: 'SPLIT_ARRANGER_CLIP', clipId, splitAtBeat }),
  toggleClipPatternStep: (clipId: string, stepIndex: number, note?: string, mode?: 'add' | 'remove' | 'toggle') => dispatch({ type: 'TOGGLE_CLIP_PATTERN_STEP', clipId, mode, note, stepIndex }),
  toggleMute: (trackId: string) => dispatch({ type: 'TOGGLE_MUTE', trackId }),
  togglePatternStep: (trackId: string, patternIndex: number, stepIndex: number, note?: string) => dispatch({ type: 'TOGGLE_PATTERN_STEP', note, patternIndex, stepIndex, trackId }),
  togglePinnedTrack: (trackId: string) => dispatch({ type: 'TOGGLE_PINNED_TRACK', trackId }),
  toggleSettings: () => dispatch({ type: 'TOGGLE_SETTINGS' }),
  toggleSolo: (trackId: string) => dispatch({ type: 'TOGGLE_SOLO', trackId }),
  toggleStep: (trackId: string, stepIndex: number, note?: string) => dispatch({ type: 'TOGGLE_STEP', note, stepIndex, trackId }),
  transformClipPattern: (clipId: string, transform: 'clear' | 'double-density' | 'halve-density' | 'randomize-velocity' | 'reset-automation' | 'shift-left' | 'shift-right' | 'transpose', value?: number) => dispatch({ type: 'TRANSFORM_CLIP_PATTERN', clipId, transform, value }),
  transposePattern: (trackId: string, semitones: number) => dispatch({ type: 'TRANSPOSE_PATTERN', semitones, trackId }),
  transposePatternAt: (trackId: string, patternIndex: number, semitones: number) => dispatch({ type: 'TRANSPOSE_PATTERN_AT', semitones, trackId, patternIndex }),
  undo: () => dispatch({ type: 'UNDO' }),
  updateArrangerClip: (clipId: string, updates: Partial<ArrangementClip>) => dispatch({ type: 'UPDATE_ARRANGER_CLIP', clipId, updates }),
  updateClipPatternAutomationStep: (clipId: string, stepIndex: number, lane: 'level' | 'tone', value: number) => dispatch({ type: 'UPDATE_CLIP_PATTERN_AUTOMATION_STEP', clipId, stepIndex, lane, value }),
  updateClipPatternStepEvent: (clipId: string, stepIndex: number, noteIndex: number, updates: Partial<NoteEvent>) => dispatch({ type: 'UPDATE_CLIP_PATTERN_STEP_EVENT', clipId, noteIndex, stepIndex, updates }),
  updatePatternAutomationStep: (trackId: string, patternIndex: number, stepIndex: number, lane: 'level' | 'tone', value: number) => dispatch({ type: 'UPDATE_PATTERN_AUTOMATION_STEP', trackId, patternIndex, stepIndex, lane, value }),
  updatePatternStepEvent: (trackId: string, patternIndex: number, stepIndex: number, noteIndex: number, updates: Partial<NoteEvent>) => dispatch({ type: 'UPDATE_PATTERN_STEP_EVENT', noteIndex, stepIndex, trackId, patternIndex, updates }),
  updateSampleSlice: (trackId: string, sliceIndex: number, updates: Partial<SampleSliceMemory>) => dispatch({ type: 'UPDATE_SAMPLE_SLICE', sliceIndex, trackId, updates }),
  updateSongMarker: (markerId: string, updates: Partial<{ beat: number; name: string }>) => dispatch({ type: 'UPDATE_SONG_MARKER', markerId, updates }),
  updateStepEvent: (trackId: string, stepIndex: number, noteIndex: number, updates: Partial<NoteEvent>) => dispatch({ type: 'UPDATE_STEP_EVENT', noteIndex, stepIndex, trackId, updates }),
  updateTrackPan: (trackId: string, pan: number) => dispatch({ type: 'TOGGLE_PAN', pan, trackId }),
  updateTrackVolume: (trackId: string, volume: number) => dispatch({ type: 'TOGGLE_VOLUME', trackId, volume }),
});
